M48
; DRILL file {KiCad 9.0.1} date 2025-07-04T09:36:58-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-04T09:36:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1024
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1495
%
G90
G05
T1
X4.6683Y-3.49
T2
X4.9617Y-3.49
T3
X2.9577Y-4.936
X3.1166Y-4.936
X3.2677Y-4.936
X3.4266Y-4.936
T4
X2.675Y-3.35
X2.675Y-4.85
X8.575Y-3.35
X8.575Y-4.85
M30
