M48
; DRILL file {KiCad 9.0.1} date 2025-06-03T12:38:32-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-03T12:38:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1024
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1495
%
G90
G05
T1
X5.2867Y-4.14
T2
X4.9933Y-4.14
T3
X3.2827Y-5.586
X3.4416Y-5.586
X3.5927Y-5.586
X3.7516Y-5.586
T4
X3.0Y-4.0
X3.0Y-5.5
X7.0Y-4.0
X7.0Y-5.5
M30
